In [1]:
import pandas as pd

In [5]:
# Load datasets
df_income = pd.read_csv('../data/raw/income_district.csv')
df_poverty = pd.read_csv('../data/raw/poverty_district.csv')
df_gini = pd.read_csv('../data/raw/gini_district.csv')
df_amenities = pd.read_csv('../data/raw/amenities.csv')

print(df_income.head(5))
print(df_poverty.head(5))
print(df_gini.head(5))
print(df_amenities.head(5))

   state     district        date  income_mean  income_median
0  Johor   Batu Pahat  2019-01-01         7392           6504
1  Johor   Batu Pahat  2022-01-01         7419           6347
2  Johor  Johor Bahru  2019-01-01         9315           7342
3  Johor  Johor Bahru  2022-01-01         9869           8232
4  Johor       Kluang  2019-01-01         5953           4933
   state     district        date  poverty_absolute  poverty_relative
0  Johor   Batu Pahat  2019-01-01               2.9               9.0
1  Johor   Batu Pahat  2022-01-01               5.1              19.4
2  Johor  Johor Bahru  2019-01-01               3.3              12.8
3  Johor  Johor Bahru  2022-01-01               3.7              10.4
4  Johor       Kluang  2019-01-01               5.0              24.9
   state     district        date   gini
0  Johor   Batu Pahat  2019-01-01  0.295
1  Johor   Batu Pahat  2022-01-01  0.338
2  Johor  Johor Bahru  2019-01-01  0.388
3  Johor  Johor Bahru  2022-01-01  0.359
4  

In [24]:
# Income dataset
df_income.shape

(318, 5)

In [25]:
df_income.columns

Index(['state', 'district', 'date', 'income_mean', 'income_median'], dtype='object')

In [26]:
df_income['date'] = pd.to_datetime(df_income['date'])
df_income['year'] = df_income['date'].dt.year

df_income['year'].unique()

array([2019, 2022], dtype=int32)

In [27]:
# Poverty dataset
df_poverty.shape

(318, 5)

In [28]:
df_poverty.columns

Index(['state', 'district', 'date', 'poverty_absolute', 'poverty_relative'], dtype='object')

In [29]:
df_poverty['date'] = pd.to_datetime(df_poverty['date'])
df_poverty['year'] = df_poverty['date'].dt.year

df_poverty['year'].unique()

array([2019, 2022], dtype=int32)

In [30]:
# Gini dataset
df_gini.shape

(318, 4)

In [31]:
df_gini.columns

Index(['state', 'district', 'date', 'gini'], dtype='object')

In [32]:
df_gini['date'] = pd.to_datetime(df_gini['date'])
df_gini['year'] = df_gini['date'].dt.year

df_gini['year'].unique()

array([2019, 2022], dtype=int32)

In [33]:
# Amenities dataset
df_amenities.shape

(496, 6)

In [34]:
df_amenities.columns

Index(['date', 'state', 'district', 'piped_water', 'sanitation',
       'electricity'],
      dtype='object')

In [35]:
df_amenities['date'] = pd.to_datetime(df_amenities['date'])
df_amenities['year'] = df_amenities['date'].dt.year

df_amenities['year'].unique()

array([2016, 2019, 2022], dtype=int32)

## Step 1: Print original column names

In [36]:
print("Income columns:", df_income.columns.tolist())
print("Poverty columns:", df_poverty.columns.tolist())
print("Gini columns:", df_gini.columns.tolist())
print("Amenities columns:", df_amenities.columns.tolist())

Income columns: ['state', 'district', 'date', 'income_mean', 'income_median', 'year']
Poverty columns: ['state', 'district', 'date', 'poverty_absolute', 'poverty_relative', 'year']
Gini columns: ['state', 'district', 'date', 'gini', 'year']
Amenities columns: ['date', 'state', 'district', 'piped_water', 'sanitation', 'electricity', 'year']


## Step 2: Standardize column names (strip whitespace and convert to lowercase)

In [37]:
df_income.columns = df_income.columns.str.strip().str.lower()
df_poverty.columns = df_poverty.columns.str.strip().str.lower()
df_gini.columns = df_gini.columns.str.strip().str.lower()
df_amenities.columns = df_amenities.columns.str.strip().str.lower()

## Step 3: Print standardized column names to confirm

In [38]:
print("Income columns (standardized):", df_income.columns.tolist())
print("Poverty columns (standardized):", df_poverty.columns.tolist())
print("Gini columns (standardized):", df_gini.columns.tolist())
print("Amenities columns (standardized):", df_amenities.columns.tolist())

Income columns (standardized): ['state', 'district', 'date', 'income_mean', 'income_median', 'year']
Poverty columns (standardized): ['state', 'district', 'date', 'poverty_absolute', 'poverty_relative', 'year']
Gini columns (standardized): ['state', 'district', 'date', 'gini', 'year']
Amenities columns (standardized): ['date', 'state', 'district', 'piped_water', 'sanitation', 'electricity', 'year']


## Step 4: Check overlapping years across all DataFrames

In [39]:
# Get unique years from each DataFrame
years_income = set(df_income['year'].unique())
years_poverty = set(df_poverty['year'].unique())
years_gini = set(df_gini['year'].unique())
years_amenities = set(df_amenities['year'].unique())

print("Years in Income:", sorted(years_income))
print("Years in Poverty:", sorted(years_poverty))
print("Years in Gini:", sorted(years_gini))
print("Years in Amenities:", sorted(years_amenities))

Years in Income: [np.int32(2019), np.int32(2022)]
Years in Poverty: [np.int32(2019), np.int32(2022)]
Years in Gini: [np.int32(2019), np.int32(2022)]
Years in Amenities: [np.int32(2016), np.int32(2019), np.int32(2022)]


In [40]:
# Find overlapping years across all four DataFrames
overlapping_years = years_income & years_poverty & years_gini & years_amenities

print("\nOverlapping years across all four DataFrames:", sorted(overlapping_years))


Overlapping years across all four DataFrames: [np.int32(2019), np.int32(2022)]
